# Generated by Django 2.2.4 on 2019-09-15 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='organizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slack_org_id', models.CharField(max_length=50, unique=True)),
                ('channel_name', models.CharField(max_length=50)),
                ('channel_id', models.CharField(max_length=50)),
                ('access_token', models.CharField(max_length=200)),
                ('installation_date', models.DateTimeField(verbose_name='installation date')),
                ('bot_access_token', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_mem_id', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('avatar', models.CharField(max_length=500)),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slack.organizations')),
            ],
        ),
        migrations.CreateModel(
            name='shoutouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=5000)),
                ('timestamps', models.DateTimeField(verbose_name='timestamp')),
                ('message_ts', models.CharField(max_length=500)),
                ('giver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slack.users')),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_id', to='slack.users')),
            ],
        ),
    ]
